# -*- coding: utf-8 -*-
"""CBM_DNASequencing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tiBwz-hKc6-PX1XuMuGJR-ktvKd01eK5
"""

#Load small data

!wget --no-check https://public.bmi.inf.ethz.ch/teaching/cbm1_2019/project1/data_small/genome.chr22.5K.fa

# read chr22
def readgeno(filename):
  geno=''
  with open(filename,'r') as f:
    for line in f:
      #ingnore header line
      if not line[0] =='>':
       geno += line.rstrip()
  return geno

chr22=readgeno('genome.chr22.5K.fa')

def readFastq(filename):
  reads=[]
  qualities=[]
  with open(filename,'r') as fh:
    while True:
      fh.readline()
      read=fh.readline().rstrip()
      fh.readline()
      quality=fh.readline().rstrip()
      if len(read) == 0:
        break
      reads.append(read)
      qualities.append(quality)
  return reads,qualities

from google.colab import files
uploaded = files.upload()

tiny1, _ =readFastq('output_tiny_30xCov1.fq')
tiny2, _ =readFastq('output_tiny_30xCov2.fq')
print(len(tiny1),len(tiny2))

def readsam(filename):
  sam=''
  with open(filename,'r') as s:
    for line in s:
       sam += line.rstrip()
  return sam

readsam('output_tiny_30xCov.mod.sam')